### ISSUE TITLE
这个要怎么用？

### ISSUE THREAD

**Issue by edonlu** [leontius/rrshare#3]
我弄好了，网页能打开，也能搜索到资源，但是下载进度一直是0，貌似也没有啥说明文件？

用的人还太少吧？

下载地址是yyets://开头的格式么？那就是说，这地址普通下载工具是下载不下来的？

**Comment by leontius** [comment]
现在YYETS可能更新软件了，我准备更新一版。

**Comment by leontius** [comment]
![image](https://user-images.githubusercontent.com/5589032/45896751-a78ec400-be07-11e8-8d26-d17d58100530.png)
编译了最新版本，可以下载了。
